### ISSUE TITLE
BepInEx compatibility

### ISSUE THREAD

**Issue by Di-ref** [Gh0stD14l3r/Dinkum-Mod-Menu-Internal-#1]
can this mod work with BepInEx ?

**Comment by Gh0stD14l3r** [comment]
The current release is for injecting only. I will look into creating a DLL so softmodders can use with BepInEx aswell. Check back in a day or so.

**Comment by Di-ref** [comment]
Fantastic ! appreciate your effort

ps : if you want more people to use your mod you can share the dll on nexusmods, many softmodders use their mod manager too

**Comment by Gh0stD14l3r** [comment]
I would most likely keep it as its own loader without using BepInEx. As this is one project in many it will be too hard to keep going with constant updates.

Also a new loader has been added to simplify the process of injecting into the game.
